### ISSUE TITLE
Could you add this

### ISSUE THREAD

**Issue by Umotas** [rkkr/tiny-keyboard#12]
Now 'android:keyOutputText="some text" ' doesn't work.
I found that this code should be added for the result:
`@Override public void onText(CharSequence text) {
InputConnection ic = getCurrentInputConnection();
ic.commitText(text, 0);
}`
Could you add this feature

**Comment by rkkr** [comment]
You're making your own layout in `qwerty.xml` and adding button that input a text sequence? You can then add this code into your own fork. This shouldn't work for inputs that only accept key clicks.

**Comment by Umotas** [comment]
> You're making your own layout in qwerty.xml and adding button that input a text sequence?
Yes, I added 
`android:popupKeyboard="@xml/popup_template" android:popupCharacters="ÜÖ" `
And I add file popup_template.
And in dimen.xml: key_heigh =58.0
All are working. But Now I cannot compile my fork. I am user only :)

**Comment by rkkr** [comment]
If you're touching code then you're a developer.

**Comment by Umotas** [comment]
No, I see your simple keyboard :)
