### ISSUE TITLE
signing key changed

### ISSUE THREAD

**Issue by IzzySoft** [rkkr/tiny-keyboard#13]
It seems like you've changed the signing key, so the currently latest release was rejected by the updater here at IzzyOnDroid:

```
2024-11-01 19:44:33,648 WARNING: "rkr.tinykeyboard.inputmethod_10.apk" is signed by a key that is not allowed:
c0046c33e90f1517081f651ad546ffbf52b4014c0d220eb3a7cd9c8ab3490c89
```

Checking, the previous release used

```
Signer #1 certificate DN: CN=Raimondas Rimkus, L=Vilnius, ST=Lithuania, C=03205
Signer #1 certificate SHA-256 digest: 12f0750bf1607469764f8acf0db67ae1cef3a6a5e1f097504e642e6edbd10e4e
Signer #1 certificate SHA-1 digest: 1b42f40f9e2abb74583923b72cc01625f4c1ab6a
Signer #1 certificate MD5 digest: 4c2eebb29476a1131a7325ab0dd63bd3
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

while the current one uses

```
Signer #1 certificate DN: CN=Raimondas Rimkus
Signer #1 certificate SHA-256 digest: c0046c33e90f1517081f651ad546ffbf52b4014c0d220eb3a7cd9c8ab3490c89
Signer #1 certificate SHA-1 digest: 280bffcee78d5d036252e3d0531dcee3cc1806fa
Signer #1 certificate MD5 digest: 907101cea870d1ae516476bfcb31249a
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

Hence updates are impossible, as Android will reject them for security reasons (could be someone else tried to push in a malicious update). I was looking at the release notes, but found no hint.

What happened? Can we solve this, and re-enable updates then? Thanks in advance!

**Comment by rkkr** [comment]
Might be the bundle key. Will check.

**Comment by rkkr** [comment]
Updated the attached release apk.

**Comment by IzzySoft** [comment]
Thanks! That looks good, proper key back :partying_face:

While here:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

(or, as the log has it:

```
! repo/rkr.tinykeyboard.inputmethod_10.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

). That can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

If you could do that for future releases (one should not change releases already distributed – this one was an exception), that would be great! And speaking of: it seems your "release frequency" has sped up lately. Should we switch back from monthly to daily update checks for your app here at IzzyOnDroid, to avoid delays?

**Comment by rkkr** [comment]
Don't get your hopes up. This was just an Android 15 SDK update and fixes for issues caused by it. Next will probably be in ~2 years. If you want change signing settings you can build from source and sign with your own keys like F-Droid does it.

**Comment by IzzySoft** [comment]
It was just checking what makes most sense – so as you describe it, monthly checks should be fine and we simply leave it at that. Should the situation change, just let us know.

And no, we do not sign with our own keys at IzzyOnDroid, not even plans for that. We do offer [Reproducible Builds](https://reproducible-builds.org/), though – but those work differently here (asynchronous), see e.g. [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients). I've tried tiny-keyboard, but it failed: the checksum of `classes.dex` doesn't match. May I ask what JDK you use to build? Here it's OpenJDK-17 on Debian bookworm. We can also use OpenJDK-11 or -21 here if you're using one of those.

Btw: don't you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [your app at IzzyOnDroid](https://apt.izzysoft.de/packages/rkr.tinykeyboard.inputmethod) from your Readme? That Google badge there looks a bit lonely :wink:
