### ISSUE TITLE
[fr] Spanish layout

### ISSUE THREAD

**Issue by throwaway242685** [rkkr/tiny-keyboard#14]
hi, are there any plans to implement a Spanish layout?

the only thing that's keeping me from using this keyboard is the inability to use the letter `ñ` and/or add accents to letters like this: `á, é, í, ó, ú`

I love the philosophy of this keyboard, but I can't really use it because of that.

**Comment by rkkr** [comment]
Not planned as this then brings in the language switching code and settings to pick the languages. You can make your own layout easily by modifying https://github.com/rkkr/tiny-keyboard/blob/master/app/src/main/res/xml/qwerty.xml . You'll only need to reduce `keyWidth` if you'll want to add more than 10 keys in a row.

**Comment by throwaway242685** [comment]
I'm not an Android developer, tho.

**Comment by rkkr** [comment]
No better place to start with than this trivial project.
